apiVersion: v1
kind: Service
metadata:
  name: pravega-grpc-gateway
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{ .Values.app }}
    component: pravega-grpc-gateway
    release: {{ .Release.Name }}
  type: NodePort
