apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  name: pravega-grpc-gateway
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{ .Values.app }}
    component: pravega-grpc-gateway
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
